#!/bin/bash
clear
if (( $# > 0 )); then
	while (( $# > 0 )); do
		_file=$1
		shift
		gd $_file
		git add $_file
	done
else
	gd
	git add -A
fi
printf "\033[0;37mCommit message: \033[0m"
read -r
git commit -m "$REPLY"
